# Generated by Django 4.1.5 on 2023-08-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_customer_age_customer_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
