# Generated by Django 4.1.5 on 2023-08-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_loan_total_fees_alter_payment_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
