# Generated by Django 4.1.5 on 2023-08-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_loan_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='total_fees',
        ),
    ]
