# Generated by Django 4.1.5 on 2023-08-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_remove_loan_total_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='total_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
