# Generated by Django 4.1.5 on 2023-08-15 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_loan_total_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='total_money',
        ),
    ]
