from django.urls import path
from rest_framework_simplejwt import views as jwt_views

from . import views

urlpatterns = [
    path(
        "api/token/", 
        jwt_views.TokenObtainPairView.as_view(), 
        name="token_obtain_pair"
    ),
    path(
        "api/token/refresh/", 
        jwt_views.TokenRefreshView.as_view(), 
        name="token_refresh"
    ),
    path(
        'token/verify/', 
        jwt_views.TokenVerifyView.as_view(), 
        name='token_verify'
    ),
    path(
        'logout', 
        views.UserLogout.as_view(), 
        name='logout'
    ),
    path(
        'login', 
        views.LoginView.as_view(), 
        name='login'
    ),
    path(
        "signup/", 
        views.RegisterUserAPIView.as_view(), 
        name="signup"
    ),
    path(
        "registerprovider/",
        views.RegisterProviderAPIView.as_view(),
        name="registerprovider",
    ),
    path(
        "registercustomer/",
        views.RegisterCustomerAPIView.as_view(),
        name="registercustomer",
    ),
    path(
        "registerpersonnel/",
        views.RegisterPersonnelAPIView.as_view(),
        name="registerpersonnel",
    ),
    path(
        "personnelloan", 
        views.loan_Personeldetail, 
        name="personnelloan"
    ),
    path(
        "coustmerloan/<int:id>/", 
        views.loan_Coustmedetail, 
        name="coustmerloan"
    ),
    path(
        "viewloan", 
        views.viewloanAPIView, 
        name="viewloan"
    ),
    path(
        "viewcoustmer", 
        views.viewCoustmerAPIView, 
        name="viewcoustmer"
    ),
    path(
        "payment/<int:id>/", 
        views.PaymentApi, 
        name="payment"
    ),
]
